<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>FluentPOS.Modules.Organizations</RootNamespace>
    <AssemblyName>FluentPOS.Modules.Organizations</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>FluentPOS.Modules.Organizations.xml</DocumentationFile>
    <CodeAnalysisRuleSet>..\..\..\fluentpos.ruleset</CodeAnalysisRuleSet>
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>FluentPOS.Modules.Organizations.xml</DocumentationFile>
    <CodeAnalysisRuleSet>..\..\..\fluentpos.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\..\..\stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules.Organizations.Infrastructure\Modules.Organizations.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules.Organizations.Core\Modules.Organizations.Core.csproj" />
  </ItemGroup>

</Project>
