<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>FluentPOS.Modules.People.Infrastructure</RootNamespace>
    <AssemblyName>FluentPOS.Modules.People.Infrastructure</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>FluentPOS.Modules.People.Infrastructure.xml</DocumentationFile>
    <CodeAnalysisRuleSet>..\..\..\fluentpos.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>FluentPOS.Modules.People.Infrastructure.xml</DocumentationFile>
    <CodeAnalysisRuleSet>..\..\..\fluentpos.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Persistence\SeedData\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\..\..\stylecop.json" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Shared.Infrastructure\Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules.People.Core\Modules.People.Core.csproj" />
  </ItemGroup>
  
</Project>
