<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>FluentPOS.Modules.Identity.Core</RootNamespace>
    <AssemblyName>FluentPOS.Modules.Identity.Core</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>FluentPOS.Modules.Identity.Core.xml</DocumentationFile>
    <CodeAnalysisRuleSet>..\..\..\fluentpos.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>FluentPOS.Modules.Identity.Core.xml</DocumentationFile>
    <CodeAnalysisRuleSet>..\..\..\fluentpos.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.7" />
    <AdditionalFiles Include="..\..\..\stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Exceptions\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Shared.Core\Shared.Core.csproj" />
  </ItemGroup>

</Project>
