<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>FluentPOS.Modules.Inventory</RootNamespace>
    <AssemblyName>FluentPOS.Modules.Inventory</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>FluentPOS.Modules.Inventory.xml</DocumentationFile>
    <CodeAnalysisRuleSet>..\..\..\fluentpos.ruleset</CodeAnalysisRuleSet>
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>FluentPOS.Modules.Inventory.xml</DocumentationFile>
    <CodeAnalysisRuleSet>..\..\..\fluentpos.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\..\..\stylecop.json" />
  </ItemGroup>
<ItemGroup>
    <ProjectReference Include="..\Modules.Inventory.Infrastructure\Modules.Inventory.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules.Inventory.Core\Modules.Inventory.Core.csproj" />
  </ItemGroup>
</Project>
