<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>FluentPOS.Modules.Catalog.Core</RootNamespace>
    <AssemblyName>FluentPOS.Modules.Catalog.Core</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>FluentPOS.Modules.Catalog.Core.xml</DocumentationFile>
    <CodeAnalysisRuleSet>..\..\..\fluentpos.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>FluentPOS.Modules.Catalog.Core.xml</DocumentationFile>
    <CodeAnalysisRuleSet>..\..\..\fluentpos.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\..\..\stylecop.json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Shared.Core\Shared.Core.csproj" />
  </ItemGroup>
</Project>
